# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a34968dd11df2226b09dfdc8af9da4e17717d55ea76758ec84affcb5f22657ee010b08f8a631d38d9d1f0c85ebbce0fb9aadb5af6289c86fa6a5c6b6180ab9f8

test:
  secret_key_base: e7a25820b9217fc847eb80900ecd1c91644d7e770a80d601e1eac26f1de09cd4b31cf3134747e3e477302b9a22617b8f17665c16c9733b1127f887e80e21b343

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
